# Generated by Django 4.0.5 on 2022-06-17 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Posting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('image_url', models.URLField()),
                ('postname', models.CharField(max_length=50, null=True)),
                ('contents', models.TextField(default='', null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postings', to='users.user')),
            ],
            options={
                'db_table': 'postings',
            },
        ),
    ]
