# Generated by Django 4.0.5 on 2022-06-16 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_alter_user_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Posting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('image_url', models.CharField(max_length=200)),
                ('user_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postings', to='users.user')),
            ],
            options={
                'db_table': 'postings',
            },
        ),
    ]
