# Generated by Django 4.0.5 on 2022-06-17 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posting',
            name='contents',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='posting',
            name='postname',
            field=models.CharField(default='', max_length=50),
        ),
    ]
